services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .env:/app/.env
      - storage:/app/storage
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-prootsecret"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "33060:3306"

volumes:
  storage:
  db_data:
