version: "3.9"

services:
    mysql:
        image: mysql:5.7
        container_name: counter-mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
            interval: 10s
            timeout: 5s
            retries: 5

    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: counter-app
        depends_on:
            mysql:
                condition: service_healthy
        volumes:
            - ./:/var/www:delegated
            - vendor_data:/var/www/vendor
        working_dir: /var/www
        environment:
            DB_HOST: mysql
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD: root
        entrypoint: ["/usr/local/bin/entrypoint.sh"]
        ports:
            - "8000:8000"

    node:
        image: node:16
        container_name: counter-node
        depends_on:
            - app
        volumes:
            - ./:/var/www:delegated
            - vendor_data:/var/www/vendor
            - node_modules:/var/www/node_modules
        working_dir: /var/www
        command: >
            sh -c "npm install && npm run build"
        ports:
            - "5173:5173"

volumes:
    mysql_data:
    vendor_data:
    node_modules:
